---
title: "assembly"
author: "Group 2"
date: "7/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, cache = T, fig.width=8, fig.height=4,
                      warning = F)
options(scipen = 0, digits = 3)

if(!require('pacman')) install.packages('pacman')

pacman::p_load(Rcpp, geofacet, tidyverse, dplyr, ggplot2, data.table, lubridate, plotROC, usmap, glmnet, 
               plotly, haven, magrittr, Stat2Data, skimr, GGally, rvest, gridExtra, scales)
```

```{r read data}
####annual aqi####
data2020.yr <- fread("data/annual_aqi_by_county_2020.csv", stringsAsFactors = TRUE)
data2019.yr <- fread("data/annual_aqi_by_county_2019.csv", stringsAsFactors = TRUE)
data2018.yr <- fread("data/annual_aqi_by_county_2018.csv", stringsAsFactors = TRUE)
data2017.yr <- fread("data/annual_aqi_by_county_2017.csv", stringsAsFactors = TRUE)
data2016.yr <- fread("data/annual_aqi_by_county_2016.csv", stringsAsFactors = TRUE)
data2015.yr <- fread("data/annual_aqi_by_county_2015.csv", stringsAsFactors = TRUE)
data2014.yr <- fread("data/annual_aqi_by_county_2014.csv", stringsAsFactors = TRUE)
data2013.yr <- fread("data/annual_aqi_by_county_2013.csv", stringsAsFactors = TRUE)
data2012.yr <- fread("data/annual_aqi_by_county_2012.csv", stringsAsFactors = TRUE)
data2011.yr <- fread("data/annual_aqi_by_county_2011.csv", stringsAsFactors = TRUE)
data2010.yr <- fread("data/annual_aqi_by_county_2010.csv", stringsAsFactors = TRUE)

####daily aqi####
data2020.day <- fread("data/daily_aqi_by_county_2020.csv", stringsAsFactors = TRUE)
data2019.day <- fread("data/daily_aqi_by_county_2019.csv", stringsAsFactors = TRUE)
data2018.day <- fread("data/daily_aqi_by_county_2018.csv", stringsAsFactors = TRUE)
data2017.day <- fread("data/daily_aqi_by_county_2017.csv", stringsAsFactors = TRUE)
data2016.day <- fread("data/daily_aqi_by_county_2016.csv", stringsAsFactors = TRUE)
data2015.day <- fread("data/daily_aqi_by_county_2015.csv", stringsAsFactors = TRUE)
data2014.day <- fread("data/daily_aqi_by_county_2014.csv", stringsAsFactors = TRUE)
data2013.day <- fread("data/daily_aqi_by_county_2013.csv", stringsAsFactors = TRUE)
data2012.day <- fread("data/daily_aqi_by_county_2012.csv", stringsAsFactors = TRUE)
data2011.day <- fread("data/daily_aqi_by_county_2011.csv", stringsAsFactors = TRUE)
data2010.day <- fread("data/daily_aqi_by_county_2010.csv", stringsAsFactors = TRUE)
data2009.day <- fread("data/daily_aqi_by_county_2009.csv", stringsAsFactors = TRUE)
data2008.day <- fread("data/daily_aqi_by_county_2008.csv", stringsAsFactors = TRUE)
data2007.day <- fread("data/daily_aqi_by_county_2007.csv", stringsAsFactors = TRUE)
data2006.day <- fread("data/daily_aqi_by_county_2006.csv", stringsAsFactors = TRUE)
data2005.day <- fread("data/daily_aqi_by_county_2005.csv", stringsAsFactors = TRUE)
data2004.day <- fread("data/daily_aqi_by_county_2004.csv", stringsAsFactors = TRUE)
data2003.day <- fread("data/daily_aqi_by_county_2003.csv", stringsAsFactors = TRUE)
data2002.day <- fread("data/daily_aqi_by_county_2002.csv", stringsAsFactors = TRUE)
data2001.day <- fread("data/daily_aqi_by_county_2001.csv", stringsAsFactors = TRUE)
data2000.day <- fread("data/daily_aqi_by_county_2000.csv", stringsAsFactors = TRUE)

####yearly greenhouse gas####
airquality_ozone<- read.csv("data/OzoneNational.csv", header=T)
airquality_nitrogen<- read.csv("data/Nitrogen_DioxideNational.csv", header=T)
airquality_sulfur<-read.csv("data/Sulfur_DioxideNational.csv", header=T)
airquality_cmonoxide<- read.csv("data/Carbon_MonoxideNational.csv", header=T)
airquality_lead<- read.csv("data/LeadNational.csv", header=T)
```

```{r prepare daily data}
raw_data.day <- rbind(
  data2020.day, data2019.day, data2018.day, data2017.day, data2016.day, data2015.day, data2014.day, data2013.day, 
  data2012.day, data2011.day, data2010.day, data2009.day, data2008.day, data2007.day, data2006.day, data2005.day,
  data2004.day,data2003.day, data2002.day, data2001.day, data2000.day
)

raw_data.day <- mutate(raw_data.day, 
                       date_formatted = as.Date(Date), 
                       month = as.Date(format(date_formatted, "%Y-%m-01"))
)

raw_data.day <- rename(raw_data.day,
                       state = `State Name`,
                       county = `county Name`,
                       state.code = `State Code`,
                       county.code = `County Code`,
                       defining.parameter = `Defining Parameter`,
                       defining.site = `Defining Site`,
                       num.rep.sites = `Number of Sites Reporting`
)

counties_by_month <- group_by(raw_data.day, county, month) %>% summarise(county.mean = mean(AQI))
states_by_month <- group_by(raw_data.day, state, month) %>% summarise(state.mean = mean(AQI))
states_by_month <- group_by(states_by_month, state) %>% mutate(delta.aqi.state = state.mean - lag(state.mean))

raw_data.day <- merge(raw_data.day, counties_by_month, by=c("county", "month"))
raw_data.day <- merge(raw_data.day, states_by_month, by=c("state", "month"))
```

```{r plots daily data}
ggplot(states_by_month, aes(x = month, y = delta.aqi.state, color = state)) +
  geom_line() +
  facet_wrap( ~ state)
```


```{r prepare annual data}
raw_data.yr <- rbind(data2020.yr, data2019.yr, data2018.yr, data2017.yr, data2016.yr,
                     data2015.yr, data2014.yr, data2013.yr, data2012.yr, data2011.yr, data2010.yr)

raw_data.yr <- raw_data.yr %>% rename(
  num.days = `Days with AQI`,
  good.days = `Good Days`,
  mod.days = `Moderate Days`,
  sens.group.days = `Unhealthy for Sensitive Groups Days`,
  unhlthy.days = `Unhealthy Days`,
  very.unhlthy.days = `Very Unhealthy Days`,
  haz.days = `Hazardous Days`,
  max.aqi = `Max AQI`,
  med.aqi = `Median AQI`,
  state = State
)

raw_data.yr <- raw_data.yr %>%
  mutate(good.pct = good.days/num.days*100,
         mod.pct = mod.days/num.days*100,
         sens.group.pct = sens.group.days/num.days*100,
         unhlthy.pct = unhlthy.days/num.days*100,
         very.unhlthy.pct = very.unhlthy.days/num.days*100,
         haz.pct = haz.days/num.days*100)

mean.state.df <- raw_data.yr %>% group_by(state, Year) %>% summarize(mean.state = mean(med.aqi),
                                                                     peak.state = max(max.aqi))

raw_data.yr <- merge(raw_data.yr, mean.state.df, by=c("state", "Year"))
```

```{r plots annual data}
ggplot(raw_data.yr, aes(x = Year, y = mean.state, color = state)) +
  geom_line() +
  geom_point()

plot_usmap(regions = "state",                   
           #regions = "counties", for county level summary
           data = mean.state.df,
           values = "mean.state", exclude = c("District of Columbia", "Country of Mexico",
                                              "Virgin Islands", "Puerto Rico")
           , color = "black") + 
  scale_fill_gradient(
    low = "white", high = "red", 
    name = "AQI", 
    label = scales::comma) + 
  labs(title = "state Avg AQI") +
  theme(legend.position = "right") +
  facet_wrap(~ Year)

#EDA
airquality_nitrogen <- mutate(airquality_nitrogen, 
                              nitrogen_concentration = airquality_nitrogen$X10th.Percentile+airquality_nitrogen$X90th.Percentile)
airquality_ozone <- mutate(airquality_ozone, 
                              ozone_concentration = airquality_ozone$X10th.Percentile+airquality_ozone$X90th.Percentile)
airquality_sulfur <- mutate(airquality_sulfur, 
                              sulfur_concentration = airquality_sulfur$X10th.Percentile+airquality_sulfur$X90th.Percentile)
airquality_lead <- mutate(airquality_lead, 
                              lead_concentration = airquality_lead$X10th.Percentile+airquality_lead$X90th.Percentile)
airquality_cmonoxide <- mutate(airquality_cmonoxide, 
                              cmonoxide_concentration = airquality_cmonoxide$X10th.Percentile+airquality_cmonoxide$X90th.Percentile)

#data format
str(airquality_ozone)
str(airquality_nitrogen)
str(airquality_sulfur)
str(cmonoxide_concentration)
str(lead_concentration)

#quick summary. missing values may be shown
summary(airquality_ozone)
summary(airquality_nitrogen)
summary(airquality_sulfur)
summary(cmonoxide_concentration)
summary(lead_concentration)

ozone.fit <- lm(Year~ozone_concentration, data =  airquality_ozone)
nitrogen.fit <- lm(Year~ nitrogen_concentration, data =  airquality_nitrogen)
sulfur.fit <- lm(Year~ sulfur_concentration, data =  airquality_sulfur)
cmonoxide.fit <- lm(Year~ cmonoxide_concentration, data =  airquality_cmonoxide)
lead.fit <- lm(Year~ lead_concentration, data =  airquality_lead)

ozone.temp <- select(airquality_ozone, c("Year", "X90th.Percentile"))
nitrogen.temp <- select(airquality_nitrogen, c("Year", "X90th.Percentile"))
sulfur.temp <- select(airquality_sulfur, c("Year", "X90th.Percentile"))
cmonoxide.temp <- select(airquality_cmonoxide, c("Year", "X90th.Percentile"))
lead.temp <- select(airquality_lead, c("Year", "X90th.Percentile"))
ozone.temp <- rename(ozone.temp, ozone.90Percentile = "X90th.Percentile")
nitrogen.temp <- rename(nitrogen.temp, nitrogen.90Percentile = "X90th.Percentile")
sulfur.temp <- rename(sulfur.temp, sulfur.90Percentile = "X90th.Percentile")
cmonoxide.temp <- rename(cmonoxide.temp, cmonoxide.90Percentile = "X90th.Percentile")
lead.temp <- rename(lead.temp, lead.90Percentile = "X90th.Percentile")


ppm <- merge(ozone.temp, nitrogen.temp, "Year") %>%
  merge(sulfur.temp, "Year") %>%
  merge(cmonoxide.temp, "Year") %>%
  merge(lead.temp, "Year")

###individual elmnts plots####
# #Ozone concentration by year
# fit1 <- lm(Year~ozone_concentration, data = airquality_ozone)
# ggplot(airquality_ozone , aes(x = Year, y = ozone_concentration, color = ozone_concentration)) +
#   ggtitle(" Ozone Concentration by Year") +
#   geom_line() +
#   geom_point()
# 
# #Nitrogen concentration by year
# fit1 <- lm(airquality_nitrogen$Year~ nitrogen_concentration, data =  airquality_nitrogen)
# ggplot(airquality_nitrogen , aes(x = Year, y = nitrogen_concentration, color = nitrogen_concentration)) +
#   ggtitle(" Nitrogen Concentration by Year") +
#   geom_line() +
#   geom_point()
# 
# #Sulfur concentration by year
# fit1 <- lm(airquality_sulfur$Year~ sulfur_concentration, data =  airquality_sulfur)
# ggplot(airquality_sulfur , aes(x = Year, y = sulfur_concentration, color = sulfur_concentration)) +
#   ggtitle(" Sulfur Concentration by Year") +
#   geom_line() +
#   geom_point()
# 
# #CO1 concentration by year
# fit1 <- lm(airquality_cmonoxide$Year~ cmonoxide_concentration, data =  airquality_cmonoxide)
# ggplot(airquality_cmonoxide , aes(x = Year, y = cmonoxide_concentration, color = cmonoxide_concentration)) +
#   ggtitle(" CO Concentration by Year") +
#   geom_line() +
#   geom_point()
# 
# #Lead concentration by year
# fit1 <- lm(airquality_lead$Year~ lead_concentration, data =  airquality_lead)
# ggplot(airquality_lead , aes(x = Year, y = lead_concentration, color = lead_concentration)) +
#   ggtitle(" Lead Concentration by Year") +
#   geom_line() +
#   geom_point()
```

```{r state energy sources}
url <- "https://www.nei.org/resources/statistics/state-electricity-generation-fuel-shares"
enrgy_srcs <- read_html(url) %>% html_table()

state_data <- data.frame(enrgy_srcs)
state_data <- state_data %>% rename(
  Nuclear.pct = Nuclear....,
  Coal.pct = Coal....,
  NaturalGas.pct = Natural.Gas....,
  Petroleum.pct = Petroleum....,
  Hydro.pct = Hydro....,
  Geothermal.pct = Geothermal....,
  Solar.pct = Solar...PV....,
  Wind.pct = Wind....,
  Biomass.and.Other.pct = Biomass.and.Other....
)

state_data[state_data$Hydro.pct == "(0.2)", c("Hydro.pct")] <- 0.2
state_data[state_data$Biomass.and.Other.pct == "(0.0)", c("Biomass.and.Other.pct")] <- 0.0
state_data[state_data$State == "Iowa1", c("State")] <- "Iowa"
state_data[state_data$State == "New York2", c("State")] <- "New York"

state_data %<>% mutate_at(c(
  "Nuclear.pct", 
  "Coal.pct", 
  "NaturalGas.pct", 
  "Petroleum.pct", 
  "Hydro.pct", 
  "Geothermal.pct", 
  "Solar.pct", 
  "Wind.pct", 
  "Biomass.and.Other.pct"),
  as.numeric)

data_long <- gather(state_data, "type", "pct", -State)

stateEnrgyDist <- ggplot(data_long, aes(y = pct, x = type, fill = type)) +
  geom_col() +
  coord_flip() +
  theme_bw() +
  facet_geo(~ State, move_axes = FALSE)
stateEnrgyDist
```