---
title: "assembly"
author: "Group 2"
date: "7/28/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, cache = T, fig.width=8, fig.height=4,
                      warning = F)
options(scipen = 0, digits = 3)

if(!require('pacman')) install.packages('pacman')

pacman::p_load(Rcpp, geofacet, tidyverse, dplyr, ggplot2, data.table, lubridate, plotROC, usmap, glmnet, 
               plotly, haven, magrittr, Stat2Data, skimr, GGally, rvest, gridExtra, scales, usdata, party)
```

```{r}
library(tidyverse)
library(data.table)
library(lubridate)
library(ggplot2)
library(usmap)
library(rvest)
library(gridExtra)
library(usdata)
library(glmnet)
library(car)

data2020 <- fread("data/annual_aqi_by_county_2020.csv", stringsAsFactors = TRUE)
data2019 <- fread("data/annual_aqi_by_county_2019.csv", stringsAsFactors = TRUE)
data2018 <- fread("data/annual_aqi_by_county_2018.csv", stringsAsFactors = TRUE)
data2017 <- fread("data/annual_aqi_by_county_2017.csv", stringsAsFactors = TRUE)
data2016 <- fread("data/annual_aqi_by_county_2016.csv", stringsAsFactors = TRUE)
data2015 <- fread("data/annual_aqi_by_county_2015.csv", stringsAsFactors = TRUE)
data2014 <- fread("data/annual_aqi_by_county_2014.csv", stringsAsFactors = TRUE)
data2013 <- fread("data/annual_aqi_by_county_2013.csv", stringsAsFactors = TRUE)
data2012 <- fread("data/annual_aqi_by_county_2012.csv", stringsAsFactors = TRUE)
data2011 <- fread("data/annual_aqi_by_county_2011.csv", stringsAsFactors = TRUE)
data2010 <- fread("data/annual_aqi_by_county_2010.csv", stringsAsFactors = TRUE)

raw_data <- rbind(data2020, data2019, data2018, data2017, data2016,
                  data2015, data2014, data2013, data2012, data2011, data2010)





raw_data <- raw_data %>% rename(
  num.days = `Days with AQI`,
  good.days = `Good Days`,
  mod.days = `Moderate Days`,
  sens.group.days = `Unhealthy for Sensitive Groups Days`,
  unhlthy.days = `Unhealthy Days`,
  very.unhlthy.days = `Very Unhealthy Days`,
  haz.days = `Hazardous Days`,
  max.aqi = `Max AQI`,
  med.aqi = `Median AQI`,
  state = State
)

raw_data$is.climate.alli <- "no"

raw_data[raw_data$state %in% c("California", "Colorado", "Connecticut", "Delaware",
                               "Hawaii", "Illinois", "Louisiana", "Maine", "Maryland",
                               "Massachucets", "Michigan", "Minnesota", "Nevada",
                               "New Jersey", "New Mexico", "New York", "North Carolina",
                               "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island",
                               "Vermont", "Virginia", "Washington", "Wisconsin"
                               ), c("is.climate.alli")] <- "yes"


raw_data <- raw_data %>%
  mutate(good.pct = good.days/num.days*100,
         mod.pct = mod.days/num.days*100,
         sens.group.pct = sens.group.days/num.days*100,
         unhlthy.pct = unhlthy.days/num.days*100,
         very.unhlthy.pct = very.unhlthy.days/num.days*100,
         haz.pct = haz.days/num.days*100)

mean.state.df <- raw_data %>% group_by(state, Year) %>% summarize(mean.state = mean(med.aqi),
                                                                  peak.state = max(max.aqi))

raw_data <- merge(raw_data, mean.state.df, by=c("state", "Year"))

subbed_data <- raw_data %>% select(state, Year, County, num.days, max.aqi, med.aqi,
                                   good.pct, mod.pct, sens.group.pct, unhlthy.pct,
                                   very.unhlthy.pct, haz.pct, mean.state, is.climate.alli)

# Analysis of the effectiveness of the climate alliance
# We take years 2017 (establishment) to 2019 to avoid outliers (2020 fires on West Coast)
subbed_data$is.climate.alli <- as.factor(subbed_data$is.climate.alli)
focus_data <- subbed_data[subbed_data$Year %in% 2016:2019,]
summary(lm(data = focus_data, med.aqi ~ is.climate.alli + state))

# The climate alliance states are on average better but its not significant


ggplot(raw_data, aes(x = Year, y = mean.state, color = state)) +
  geom_line() +
  geom_point()

plot_usmap(regions = "state",                   
           #regions = "counties", for county level summary
           data = mean.state.df,
           values = "mean.state", exclude = c("District of Columbia", "Country of Mexico",
                                                     "Virgin Islands", "Puerto Rico")
           , color = "black") + 
  scale_fill_gradient(
    low = "white", high = "red", 
    name = "AQI", 
    label = scales::comma) + 
  labs(title = "state Avg AQI") +
  theme(legend.position = "right") +
  facet_wrap(~ Year)

#Plotting of all 50 States vs Avg AQI
raw_data %>%
ggplot(aes(x = Year, y = mean.state, group=state,color = state)) +
  geom_line() +
  geom_point()+
  geom_smooth(method="lm", formula=y~x, se=F,color = "red")+
  facet_wrap(~state) +
  theme_bw() +
  theme(legend.position = 0) +
  ggtitle("`State`vs`Avg AQI")

#Pollutant trend graphs that affect air quality by year

 
#EDA
airquality_ozone<- read.csv("data/OzoneNational.csv", header=T)
airquality_nitrogen<- read.csv("data/Nitrogen_DioxideNational.csv", header=T)
airquality_sulfur<-read.csv("data/Sulfur_DioxideNational.csv", header=T)
airquality_lead<-read.csv("data/LeadNational.csv", header=T)
airquality_carbon<-read.csv("data/Carbon_MonoxideNational.csv", header=T)
airquality_PM10<-read.csv("data/PM10National.csv", header=T)
airquality_PM25<-read.csv("data/PM25National.csv", header=T)

str( airquality_nitrogen)# data format
summary( airquality_nitrogen)# quick summary. missing values may be shown
airquality_nitrogen %>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Nitrogen") +
  xlab("Year") +
  ggtitle("Nitrogen Concentration by year")

str( airquality_ozone)# data format
summary( airquality_ozone)# quick summary. missing values may be shown
 airquality_ozone %>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") +
  xlab("Year") +
  ggtitle("Ozone Concentration by year")
 
str( airquality_sulfur)# data format
summary( airquality_sulfur)# quick summary. missing values may be shown
 airquality_sulfur %>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Sulfur Dioxide") +
  xlab("Year") +
  ggtitle("Sulfur Dioxide Concentration by year")
 
str( airquality_lead)# data format
summary( airquality_lead)# quick summary. missing values may be shown
 airquality_lead %>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Lead") +
  xlab("Year") +
  ggtitle("Lead Concentration by year")
 
str( airquality_carbon)# data format
summary( airquality_carbon)# quick summary. missing values may be shown
 airquality_carbon%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Carbon Monoxide") +
  xlab("Year") +
  ggtitle("Carbon Monoxide Concentration by year")
 
str( airquality_PM10)# data format  
summary( airquality_PM10)# quick summary. missing values may be shown
 airquality_PM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("Particulate Matter 10 Concentration by year")
 
 str( airquality_PM25)# data format  
summary( airquality_PM25)# quick summary. missing values may be shown
 airquality_PM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("Particulate Matter 25 Concentration by year")
```
<<<<<<< HEAD
=======

>>>>>>> 0860526a24fc2bfbf8e5231190f09b25f74a2547
#Region wise Ozone Concentration
``` {r Region}
airquality_centralozone<-read.csv("aqi_proj/data/OzoneCentral.csv", header=T)
airquality_UpperMidwestozone<-read.csv("data/OzoneUpperMidwest.csv", header=T)
airquality_Northeastozone<-read.csv("data/OzoneNortheast.csv", header=T)
airquality_Northwestozone<-read.csv("data/OzoneNorthwest.csv", header=T)
airquality_Southozone<-read.csv("data/OzoneSouth.csv", header=T)
airquality_Southeastozone<-read.csv("data/OzoneSoutheast.csv", header=T)
airquality_Southwestozone<-read.csv("data/OzoneSouthwest.csv", header=T)
airquality_Westozone<-read.csv("data/OzoneWest.csv", header=T)
airquality_NRPozone<-read.csv("data/OzoneNorthernRockies.csv", header=T)
 
p1<-airquality_centralozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone Central")
 
  p2 <- airquality_UpperMidwestozone%>% #upper midwest
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone MW")
  
  p3 <- airquality_Northeastozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone NE")
  
  p4 <- airquality_Northwestozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone NW")
  
  p5 <- airquality_Southozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone South")
  
  p6 <- airquality_Southeastozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone SE")
    
  p7 <- airquality_Southwestozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone SW")
     
  p8 <- airquality_Westozone%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone West")
 
  p9 <- airquality_NRPozone%>% #Northern Rockies and Plains
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("Ozone") + 
  xlab("Year") +
  ggtitle("Ozone NRP") #North Rockie and Plains
 
grid.arrange(p1, p2, p3,p4,p5,p6,p7,p8,p9,  ncol=3)# facet the two plots  side by side

```

```{r Region wise Nitrogen Di oxide }
airquality_centralnitrogen<-read.csv("data/Nitrogen_DioxideCentral.csv", header=T)
airquality_UpperMidwestnitrogen<-read.csv("data/Nitrogen_DioxideUpperMidwest.csv", header=T)
airquality_Northeastnitrogen<-read.csv("data/Nitrogen_DioxideNortheast.csv", header=T)
airquality_Southnitrogen<-read.csv("data/Nitrogen_DioxideSouth.csv", header=T)
airquality_Southeastnitrogen<-read.csv("data/Nitrogen_DioxideSoutheast.csv", header=T)
airquality_Southwestnitrogen<-read.csv("data/Nitrogen_DioxideSouthwest.csv", header=T)
airquality_Westnitrogen<-read.csv("data/Nitrogen_DioxideWest.csv", header=T)
airquality_NRPnitrogen<-read.csv("data/Nitrogen_DioxideNorthernRockies.csv", header=T)

p11<-airquality_centralnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 Central")

p12 <- airquality_UpperMidwestnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 MW")

p13 <- airquality_Northeastnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 NE")

 

p14 <- airquality_Southnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 South")

p15 <- airquality_Southeastnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 SE")



p16 <- airquality_Southwestnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 SW")

p17 <- airquality_Westnitrogen%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 West")

 

p18 <- airquality_NRPnitrogen%>% #Northern Rockies and Plains
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("NO2") + 
  xlab("Year") +
  ggtitle("NO2 NRP")

grid.arrange(p11, p12, p13,p14,p15,p16,p17,p18,  ncol=3)# facet the two plots  side by side


```

```{r Regionwise Sulphurdioxide}
airquality_centralsulfurdioxide<-read.csv("data/Sulfur_DioxideCentral.csv", header=T)
airquality_UpperMidwestsulfurdioxide<-read.csv("data/Sulfur_DioxideUpperMidwest.csv", header=T)
airquality_Northeastsulfurdioxide<-read.csv("data/Sulfur_DioxideNortheast.csv", header=T)
airquality_Southsulfurdioxide<-read.csv("data/Sulfur_DioxideSouth.csv", header=T)
airquality_Southeastsulfurdioxide<-read.csv("data/Sulfur_DioxideSoutheast.csv", header=T)
airquality_Southwestsulfurdioxide<-read.csv("data/Sulfur_DioxideSouthwest.csv", header=T)
airquality_Westsulfurdioxide<-read.csv("data/Sulfur_DioxideWest.csv", header=T)
airquality_NRPsulfurdioxide<-read.csv("data/Sulfur_DioxideNorthernRockies.csv", header=T)



p21<-airquality_centralsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 Central")

p22 <- airquality_UpperMidwestsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 MW")

p23 <- airquality_Northeastsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 NE")

 

p24 <- airquality_Southsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 South")

p25 <- airquality_Southeastsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 SE")



p26 <- airquality_Southwestsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 SW")

p27 <- airquality_Westsulfurdioxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 West")

 

p28 <- airquality_NRPsulfurdioxide%>% #Northern Rockies and Plains
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("SO2") + 
  xlab("Year") +
  ggtitle("SO2 NRP")

grid.arrange(p21, p22, p23,p24,p25,p26,p27,p28,  ncol=3)# facet the two plots  side by side
```

```{r Regionwise CO}
airquality_centralcarbonmonoxide<-read.csv("data/Carbon_MonoxideCentral.csv", header=T)
airquality_UpperMidwestcarbonmonoxide<-read.csv("data/Carbon_MonoxideUpperMidwest.csv", header=T)
airquality_Northeastcarbonmonoxide<-read.csv("data/Carbon_MonoxideNortheast.csv", header=T)
airquality_Northwestcarbonmonoxide<-read.csv("data/Carbon_MonoxideNorthwest.csv", header=T)
airquality_Southcarbonmonoxide<-read.csv("data/Carbon_MonoxideSouth.csv", header=T)
airquality_Southeastcarbonmonoxide<-read.csv("data/Carbon_MonoxideSoutheast.csv", header=T)
airquality_Southwestcarbonmonoxide<-read.csv("data/Carbon_MonoxideSouthwest.csv", header=T)
airquality_Westcarbonmonoxide<-read.csv("data/Carbon_MonoxideWest.csv", header=T)
 

p41<-airquality_centralcarbonmonoxide%>% 
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO Central")

p42 <- airquality_UpperMidwestcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO MW") #Midwest

p43 <- airquality_Northeastcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO NE")

p44 <- airquality_Northwestcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO NW")

p45 <- airquality_Southcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO South")

p46 <- airquality_Southeastcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO SE")

p47 <- airquality_Southwestcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO SW")

p48 <- airquality_Westcarbonmonoxide%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("CO") + 
  xlab("Year") +
  ggtitle("CO West")

grid.arrange(p41, p42, p43,p44,p45,p46,p47,p48, ncol=3)# facet the two plots  side by side
```

```{r Regionwise PM10 echo=False}
airquality_centralPM10<-read.csv("data/PM10Central.csv", header=T)
airquality_UpperMidwestPM10<-read.csv("data/PM10UpperMidwest.csv", header=T)
airquality_NortheastPM10<-read.csv("data/PM10Northeast.csv", header=T)
airquality_NorthwestPM10<-read.csv("data/PM10Northwest.csv", header=T)
airquality_SouthPM10<-read.csv("data/PM10South.csv", header=T)
airquality_SoutheastPM10<-read.csv("data/PM10Southeast.csv", header=T)
airquality_SouthwestPM10<-read.csv("data/PM10Southwest.csv", header=T)
airquality_WestPM10<-read.csv("data/PM10West.csv", header=T)
airquality_NRPPM10<-read.csv("data/PM10NorthernRockies.csv", header=T)

p51<-airquality_centralPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 Central")

p52 <- airquality_UpperMidwestPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 MW")

p53 <- airquality_NortheastPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 NE")

p54 <- airquality_NorthwestPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 NW")

p55 <- airquality_SouthPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 South")

p56 <- airquality_SoutheastPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 SE")



p57 <- airquality_SouthwestPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 SW")

p58 <- airquality_WestPM10%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 West")
 

p59 <- airquality_NRPPM10%>% #Northern Rockies and Plains
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey60") +
  geom_line(aes(y = Mean)) +
  ylab("PM10") + 
  xlab("Year") +
  ggtitle("PM10 NRP")

grid.arrange(p51, p52, p53,p54,p55,p56,p57,p58,p59, ncol=3)# facet the two plots  side by side
```

```{r Regionwise PM25}
airquality_centralPM25<-read.csv("data/PM25Central.csv", header=T)
airquality_UpperMidwestPM25<-read.csv("data/PM25UpperMidwest.csv", header=T)
airquality_NortheastPM25<-read.csv("data/PM25Northeast.csv", header=T)
airquality_NorthwestPM25<-read.csv("data/PM25Northwest.csv", header=T)
airquality_SouthPM25<-read.csv("data/PM25South.csv", header=T)
airquality_SoutheastPM25<-read.csv("data/PM25Southeast.csv", header=T)
airquality_SouthwestPM25<-read.csv("data/PM25Southwest.csv", header=T)
airquality_WestPM25<-read.csv("data/PM25West.csv", header=T)
airquality_NRPPM25<-read.csv("data/PM25NorthernRockies.csv", header=T)

p61<-airquality_centralPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 Central")

p62 <- airquality_UpperMidwestPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 MW")

p63 <- airquality_NortheastPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 NE")

p64 <- airquality_NorthwestPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 NW")

p65 <- airquality_SouthPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 South")

p66 <- airquality_SoutheastPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 SE")



p67 <- airquality_SouthwestPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 SW")

p68 <- airquality_WestPM25%>%
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 West")
 
p69 <- airquality_NRPPM25%>% #Northern Rockies and Plains
  ggplot(aes(x=Year )) +
  geom_ribbon(aes(ymin = X10th.Percentile, ymax = X90th.Percentile), fill = "grey70") +
  geom_line(aes(y = Mean)) +
  ylab("PM25") + 
  xlab("Year") +
  ggtitle("PM25 NRP")

grid.arrange(p61, p62, p63,p64,p65,p66,p67,p68,p69, ncol=3)# facet the two plots  side by side
```

``` {r}
 url <- "https://www.nei.org/resources/statistics/state-electricity-generation-fuel-shares"
 data1 <- read_html(url) %>% html_table()
 state_data <- data.frame(data1[1])
 state_data <- state_data %>% rename(
   state = State,
   Nuclear.pct = Nuclear....,
   Coal.pct = Coal....,
   NaturalGas.pct = Natural.Gas....,
   Petroleum.pct = Petroleum....,
   Hydro.pct = Hydro....,
   Geothermal.pct = Geothermal....,
   Solar.pct = Solar...PV....,
   Wind.pct = Wind....,
   Biomass.and.Other.pct = Biomass.and.Other....
 )
 state_data[state_data$Hydro.pct == "(0.2)", c("Hydro.pct")] <- 0.2
 state_data[state_data$Biomass.and.Other.pct == "(0.0)", c("Biomass.and.Other.pct")] <- 0.0
 state_data[state_data$state == "Iowa1", c("state")] <- "Iowa"
 state_data[state_data$state == "New York2", c("state")] <- "New York"
 state_data$Nuclear.pct <- as.numeric(state_data$Nuclear.pct)
 state_data$Coal.pct <- as.numeric(state_data$Coal.pct)
 state_data$NaturalGas.pct <- as.numeric(state_data$NaturalGas.pct)
 state_data$Petroleum.pct <- as.numeric(state_data$Petroleum.pct)
 state_data$Hydro.pct <- as.numeric(state_data$Hydro.pct)
 state_data$Geothermal.pct <- as.numeric(state_data$Geothermal.pct)
 state_data$Solar.pct <- as.numeric(state_data$Solar.pct)
 state_data$Wind.pct <- as.numeric(state_data$Wind.pct)
 state_data$Biomass.and.Other.pct <- as.numeric(state_data$Biomass.and.Other.pct)
 data_long <- state_data %>%
   tidyr::gather("type", "pct", -state)
 
 energy.aqi.join <- merge(mean.state.df[mean.state.df$Year == 2020, ], state_data, by = c("state"))
```
 
 
``` {r CountyImpact}

set.seed(1)

# how does the socioeconomic status of a county impact air quality?
county_data_jobs <- fread("data/Release23_June2021/Jobs.csv")
county_data_people <- fread("data/Release23_June2021/People.csv")
county_data_income <- fread("data/Release23_June2021/Income.csv")


county_data_master <- merge(county_data_jobs, county_data_people, by = c("County", "FIPS", "State"))
county_data_master <- merge(county_data_master, county_data_income, by = c("County", "FIPS", "State"))
county_data_master$State <- abbr2state(county_data_master$State)
county_data_master <- county_data_master %>% rename(state = State)

dated_subbed_data <- subbed_data[subbed_data$Year == 2019,] %>% select(state, Year, County, med.aqi)

master_data <- merge(county_data_master, dated_subbed_data, by = c("County", "state"))

glmnet_data <- master_data %>% select(-County, -FIPS) %>% drop_na()

X <- model.matrix(med.aqi~., glmnet_data)[,-1]
y <- glmnet_data$med.aqi

state_ind <- c(rep(0, 48), rep(1, ncol(X)-48))

fit.cv <- cv.glmnet(X, y, alpha = 1, nfolds = 10)

coeffs <- coef(fit.cv)
nonzeros <- rownames(as.matrix(coeffs[which(coeffs != 0), 0]))
non_state_intercept_coef <- nonzeros[10:length(nonzeros)]

select_cols <- c("state", "med.aqi", non_state_intercept_coef)
lm_cols <- glmnet_data %>% select(select_cols)

fit.lm <- lm(data = lm_cols, med.aqi ~ .)
summary(fit.lm)
```
 
``` {r Backward Selection 1}
fit.backward.1 <- update(fit.lm, .~. -Age65AndOlderPct2010)
Anova(fit.backward.1)
```

```{r backward 2}
fit.backward.2 <- update(fit.backward.1, .~. - PctEmpAgriculture)
Anova(fit.backward.2)
```

```{r backward 2}
fit.backward.3 <- update(fit.backward.2, .~. - PctEmpConstruction)
Anova(fit.backward.3)
fit.final <- fit.backward.3
```

``` {r experimental}
aq<-read_csv("data/daily_42101_2021.csv")

aq %>% filter(`Pollutant Standard`=="CO 1-hour 1971") %>% ggplot(aes(x= `Date Local`,y=`Arithmetic Mean`,colour=`State Name`)) + geom_point() +geom_smooth()+ facet_wrap(. ~ `State Name`,scales = "free_y")
```
